### ISSUE TITLE
Add Package "exstatsd"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1021]
Add the Package "exstatsd" from hex.pm

Link: https://hex.pm/packages/exstatsd

Description: 
An Elixir ports client for StatsD

**Comment by upbit** [comment]
It's my mistake, I don't see the [CargoSense/ex_statsd](https://github.com/CargoSense/ex_statsd) before I wrote exstatsd.

Use [ex_statsd](https://hex.pm/packages/ex_statsd) instead. Package exstatsd is abandoned.
