### ISSUE TITLE
Add Package "geocalc"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1053]
Add the Package "geocalc" from hex.pm

Link: https://hex.pm/packages/geocalc

Description:

**Comment by yltsrc** [comment]
would be nice to see it in Geolocation section

**Comment by yltsrc** [comment]
my pull request https://github.com/h4cc/awesome-elixir/pull/1059

**Comment by h4cc** [comment]
Done :smile:

**Comment by yltsrc** [comment]
thanks :)
