### ISSUE TITLE
Elixir in Action has the wrong year

### ISSUE THREAD

**Issue by sotojuan** [h4cc/awesome-elixir#1099]
In the Books section, it says Elixir in Action was released in 2014. In fact, it was released this year.

Source: https://www.manning.com/books/elixir-in-action

**Comment by sotojuan** [comment]
Fixed in 6590ca3e0ed2747df8e96562f95881e740a83b1d.

**Comment by h4cc** [comment]
Thanks for the hint. I think when i added it it was still a "beta" or such.
