### ISSUE TITLE
Add Package "termcap"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1104]
Add the Package "termcap" from hex.pm

Link: https://hex.pm/packages/termcap

Description: 
Pure erlang termcap library

**Comment by hlship** [comment]
I'd be nervous about a package that doesn't have documentation, hasn't been updated in 2 years, and doesn't have a github link. That being said, this seems to be the source: https://github.com/project-fifo/etermcap

**Comment by h4cc** [comment]
Yep, me too. Thanks!
