### ISSUE TITLE
Add Package "curtains"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1108]
Add the Package "curtains" from hex.pm

Link: https://hex.pm/packages/curtains

Description: 
Curtains is a Elixir package that "takes over" your Elixir website by returning content of a specified file (if it exists). This makes it perfect for "Under construction" and "Maintenance" pages. At it's heart, it's just a Plug.

**Comment by acconrad** [comment]
The package notes its still in development so isn't ready for primetime yet (and it's been 2 years), you can safely close this one out
