### ISSUE TITLE
Add Package "marked"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1508]
Add the Package "marked" from hex.pm

Link: https://hex.pm/packages/marked

Description: 
CommonMark compatible Markdown parser

**Comment by igl** [comment]
Isn't the point of a "awesome" list to provide a list of proven modules one would personally recommend?
This one seems to be just everything you can find.

**Comment by h4cc** [comment]
Yep, it should. In the young context of Elixir it was awesome that there were some packages for X and thats what this started with :)

Actually there are systems more usefull for collecting like http://toolbox.elixir.pm/, which is a clone of https://www.ruby-toolbox.com/ so this awesome-list might become unnecessary someday.
