### ISSUE TITLE
Add Package "kane"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1604]
Add the Package "kane" from hex.pm

Link: https://hex.pm/packages/kane

Description: 
A library for interacting with Google Cloud Pub/Sub (PubSub).
Supports both publication and pull subscription

**Comment by peburrows** [comment]
This issue can be closed (was closed by https://github.com/h4cc/awesome-elixir/pull/1725).

**Comment by h4cc** [comment]
Thanks!
