### ISSUE TITLE
Add Package "pricing"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1625]
Add the Package "pricing" from hex.pm

Link: https://hex.pm/packages/pricing

Description: 
Pricing financial instruments in Elixir

**Comment by NobbZ** [comment]
It's only version 0.0.1 according to Hex. Also the Github link there is
404. I don't think that his needs to be added...

Julius Beckmann <notifications@github.com> schrieb am Mi., 27. Jan. 2016
05:31:

**Comment by h4cc** [comment]
Yep, thanks!
