### ISSUE TITLE
Add Package "xe"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1659]
Add the Package "xe" from hex.pm

Link: https://hex.pm/packages/xe

Description: 
Real time conversion for currencies

**Comment by teerawat1992** [comment]
What is the proper category for this package `Third Party APIs` or `Text and Numbers` :thought_balloon:

**Comment by h4cc** [comment]
Since its calling a remote service, i would think so too.

**Comment by teerawat1992** [comment]
:ok_hand:
