### ISSUE TITLE
Add Package "hut"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1785]
Add the Package "hut" from hex.pm

Link: https://hex.pm/packages/hut

Description: 
helper library for making Erlang libraries logging framework agnostic

**Comment by setzer777** [comment]
Hey! The link is broken @h4cc D:

**Comment by h4cc** [comment]
Seem so. Thank!

Even when search is still listing hut: https://hex.pm/packages?search=hut&sort=downloads
