### ISSUE TITLE
Add Package "chatter"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1848]
Add the Package "chatter" from hex.pm

Link: https://hex.pm/packages/chatter

Description: 
Chatter is extracted from the ScaleSmall project as a standalone piece.
This may be used independently to broadcast messages to a set of nodes.
It uses a mixture of UDP multicast and TCP to deliver messages and tries
to minimize network traffic while doing so.

**Comment by dbeck** [comment]
Hello, let me send a PR soon for this one, thank you, David
