### ISSUE TITLE
Add Package "alice_shizzle"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1862]
Add the Package "alice_shizzle" from hex.pm

Link: https://hex.pm/packages/alice_shizzle

Description: 
A handlez fo' tha Alice Slack bot fo' realz. Allows you ta drop a rhyme like a thug by utilizin Gizoogle

**Comment by adamzaninovich** [comment]
:+1:

**Comment by adamzaninovich** [comment]
Also, this is one of several handler plugins for the [Alice Slack bot](https://github.com/adamzaninovich/alice)

**Comment by notdevinclark** [comment]
Yep, in order to use [alice_shizzle](https://github.com/notdevinclark/alice_shizzle), you need to set up an [Alice Slack bot](https://github.com/adamzaninovich/alice) and add it to it.
