### ISSUE TITLE
Add Package "mochiweb_html"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1892]
Add the Package "mochiweb_html" from hex.pm

Link: https://hex.pm/packages/mochiweb_html

Description: 
Mochiweb HTML parser

**Comment by jaimeiniesta** [comment]
I'd like to help with these issues, but let me check -- this package is already linked with its Github URL. Should we replace it with the link to Hex.pm? Or consider this issue as done?

**Comment by h4cc** [comment]
If the current link to "mochiweb" i correct, because the package here is called "mochiweb_html" - Then everything is fine :)

CONTRIBUTING.md says we link to the source repos, because package managers can differ.

Thanks for your hint :dancer:
