### ISSUE TITLE
Add Package "excollections"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#1960]
Add the Package "excollections" from hex.pm

Link: https://hex.pm/packages/excollections

Description: 
A collection of data-structures and related algorithms for Elixir, implemented in Elixir.

**Comment by metabrain** [comment]
Hey,

Just found this ticket with a google search... Much appreciated! I am still developing the project as I go along. I will publish it in a standalone repository once I finish it most of it's initial set of features.

The GitHub repo is https://github.com/metabrain/elixir-playground/tree/master/excollections in case anyone is interested.

Cheers,
Dan

**Comment by h4cc** [comment]
Thanks for the info.

This ticket was auto generated, when you published the package on hex. 

Feel free to add it via Pull-Request when ready :D
