### ISSUE TITLE
Add Package "ejwt"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2060]
Add the Package "ejwt" from hex.pm

Link: https://hex.pm/packages/ejwt

Description: 
Encode/decode JSON Web Token

**Comment by acconrad** [comment]
This issue should be closed. It's a Erlang library (not an Elixir one) and has not been updated in over 2 years and no longer appears to be in development.

**Comment by h4cc** [comment]
Thanks!
