### ISSUE TITLE
Add Package "prometheus"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2104]
Add the Package "prometheus" from hex.pm

Link: https://hex.pm/packages/prometheus

Description: 
Prometheus monitoring system and time series database client in Erlang.

**Comment by deadtrickster** [comment]
Hey, I see help wanted tag. What kind of help?

**Comment by h4cc** [comment]
Just add the links by opening a pull request.

see: https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md
