### ISSUE TITLE
Add Package "nomad"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2107]
Add the Package "nomad" from hex.pm

Link: https://hex.pm/packages/nomad

Description: 
Create cloud portable Elixir and Phoenix apps. Write once, use everywhere!

**Comment by churcho** [comment]
Can't seem to find the package on github

**Comment by h4cc** [comment]
Asked the author: https://twitter.com/h4cc/status/732546482029666305
