### ISSUE TITLE
Add Package "named_args"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2179]
Add the Package "named_args" from hex.pm

Link: https://hex.pm/packages/named_args

Description: 
Ensures default maps and keyword lists have the defaults specified.

**Comment by acconrad** [comment]
Given that Elixir has default values supported in function arguments, as well as the fact that this package has not be developed in over a year, I would push for simply closing this issue.

**Comment by h4cc** [comment]
Its a nice little package with a single fitting case. 
But a neat idea by @mgwidmann :+1:
