### ISSUE TITLE
Add Package "benchee"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2212]
Add the Package "benchee" from hex.pm

Link: https://hex.pm/packages/benchee

Description: 
Versatile (micro) benchmarking that is extensible. Get statistics such as:
average, iterations per second, standard deviation and the median.

**Comment by PragTob** [comment]
Um, hi there! (random google just lead me here) - sure would love to add it/have it added here :D

**Comment by h4cc** [comment]
But adding is a manual step, that you can do yourself :)
