### ISSUE TITLE
Add Package "pagarmex"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2264]
Add the Package "pagarmex" from hex.pm

Link: https://hex.pm/packages/pagarmex

Description: 
A PagarMe Library for Elixir.

**Comment by gullitmiranda** [comment]
@h4cc, I am the maintainer of the package `pagarmex`. what help do you need?

**Comment by h4cc** [comment]
Thanks for asking.

That issue was created automatically from hex.pm, so if you think the library should be added, create a Pull Request :)
Matching category would be "Third Party APIs" imho.

More info at CONTRIBUTING: https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md
