### ISSUE TITLE
Add Package "expug"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2327]
Add the Package "expug" from hex.pm

Link: https://hex.pm/packages/expug

Description: 
Indented shorthand templates for HTML. (pre-release)

**Comment by rstacruz** [comment]
Author here. How can I help?

**Comment by rstacruz** [comment]
On this note, I think `expug`, `calliope`, `phoenix_expug`, `phoenix_haml`, `phoenix_slime` can be put together into a new section. :-)

**Comment by h4cc** [comment]
Hi, please open a Pull Request.

See for Information: https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md
