### ISSUE TITLE
Add Package "updown"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2385]
Add the Package "updown" from hex.pm

Link: https://hex.pm/packages/updown

Description: 
A library that interacts with the updown.io API.
The library supports a few basic fetch functions that retrieves site checks and data about each of them, it also has a few edit functions that changes site checks to suit your needs.

**Comment by acconrad** [comment]
Seems like an API for a proprietary service that is still live as of today, might as well add it
