### ISSUE TITLE
Add Package "mark_yamill"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2422]
Add the Package "mark_yamill" from hex.pm

Link: https://hex.pm/packages/mark_yamill

Description: 
A YAML decoder for Elixir

**Comment by amorphid** [comment]
@h4cc Hi!  I wrote mark_yamill.  How does one help?

**Comment by h4cc** [comment]
@amorphid Read this file and add the github link to the `README.md` :) https://github.com/h4cc/awesome-elixir/blob/master/CONTRIBUTING.md

**Comment by fladson** [comment]
the file it's here now 😄 https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md
