### ISSUE TITLE
Add Package "igdb"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2445]
Add the Package "igdb" from hex.pm

Link: https://hex.pm/packages/igdb

Description: 
A few sentences (a paragraph) describing the project.

**Comment by agustif** [comment]
Hello, I was doing some research if any https://www.igdb.com/api libs made in elixir existed.

I could only found this issue as a reference, but the link to hex is broken and I dont know If I should pursue building my own lib for the API, or wait or try and contact someone doing the same effort out in the open (I just cant seem to be able to find it)

Sorry for the off-topic, but I don't know where else to ask!

**Comment by fladson** [comment]
Looks like just the hex.pm link is off, I found this package at gh - https://github.com/zedwarth/igdbex
