### ISSUE TITLE
Add Package "githubissues"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2457]
Add the Package "githubissues" from hex.pm

Link: https://hex.pm/packages/githubissues

Description: 
It fetches issues from GitHub for selected user and project.

**Comment by fladson** [comment]
gh link is returning 404

**Comment by Kentoseth** [comment]
@fladson 

Is there a way for us to find/fork that repo and re-add it to this list (and to github)?

**Comment by fladson** [comment]
@Kentoseth You have to contact the package author to do this, it's not up to us. 
You can contribute adding many more packages though, just get from the open issues.

**Comment by Kentoseth** [comment]
Noted.

Not worth chasing after the author :)
