### ISSUE TITLE
Add Package "distillery"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2485]
Add the Package "distillery" from hex.pm

Link: https://hex.pm/packages/distillery

Description: 
Build releases of your Mix projects with ease!
WARNING: This package is an experimental replacement for exrm, use at your own risk!

**Comment by Trevoke** [comment]
I think this should be in the list now, no?

**Comment by axelson** [comment]
This is already on the list so this issue can be closed
