### ISSUE TITLE
Add Package "propcheck"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2519]
Add the Package "propcheck" from hex.pm

Link: https://hex.pm/packages/propcheck

Description: 
PropCheck provides property based testing and is an Elixir layer around
PropEr. It is also inspired by Quuvic's QuickCheck Elixir library.

**Comment by totallymike** [comment]
I think it's worth adding. Here's the GH Repo: https://github.com/alfert/propcheck
