### ISSUE TITLE
Evaluate Package "syringe"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2858]
Evaluate "syringe" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/syringe

Description: 
A full library to help inject implementations at build time.
With this power we can have a strong mocking framework that 
can also be asynchronous in test.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by skylerparr** [comment]
👍
