### ISSUE TITLE
Evaluate Package "injex"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2859]
Evaluate "injex" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/injex

Description: 
A simple way to describe dependencies that can be replaced at test time.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by blatyo** [comment]
As the author of this library, I can say I use it, but it's not awesome yet.

**Comment by h4cc** [comment]
Okay :) Thanks for that honesty
