### ISSUE TITLE
Evaluate Package "confex"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2874]
Evaluate "confex" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/confex

Description: 
Helper module that provides a nice way to read environment configuration at runtime.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by AndrewDryga** [comment]
It's my module, feel free to ask questions :).

**Comment by h4cc** [comment]
Feel Free to add it to the list :)
Check out .GitHub/cotributing.md
