### ISSUE TITLE
Evaluate Package "apocryphal"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#2875]
Evaluate "apocryphal" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/apocryphal

Description: 
Elixir Hooks Worker for Dredd API Testing Framework

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by coryodaniel** [comment]
It's not awesome yet, I'd say its 'slightly cool' I plan to do a lot of work on it over the next two weekends.
