### ISSUE TITLE
Evaluate Package "carmelize"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3014]
Evaluate "carmelize" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/carmelize

Description: 
An Elixir library that converts maps from `snake_case` to `camelCase`.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by seanwash** [comment]
404, seems like a mispelled dupe of https://github.com/h4cc/awesome-elixir/issues/3016
