### ISSUE TITLE
Evaluate Package "libcluster"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3029]
Evaluate "libcluster" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/libcluster

Description: 
Automatic Erlang cluster formation and management for Elixir/Erlang applications

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by formido** [comment]
It's awesome.

**Comment by h4cc** [comment]
Thanks!
