### ISSUE TITLE
Evaluate Package "exfcm"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3060]
Evaluate "exfcm" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/exfcm

Description: 
Simple wrapper around Firebase Cloud Messaging that uses HTTPoison.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by Hajto** [comment]
You added that faster than I could think about it...
