### ISSUE TITLE
Evaluate Package "elastic"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3158]
Evaluate "elastic" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/elastic

Description: 
You Know, for (Elastic) Search

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by radar** [comment]
@h4cc I can guarantee it is awesome ;) I built it and use it in production. How can I get it added to the list?

**Comment by fladson** [comment]
@radar please check our contributing guide https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md
