### ISSUE TITLE
Evaluate Package "paladin_client"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3202]
Evaluate "paladin_client" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/paladin_client

Description: 
Provides helper functions and a Read-Through cache for interacting with Paladin

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by connorjacobsen** [comment]
Might be useful: https://labs.opendoor.com/2016/03/22/service-to-service-with-paladin
