### ISSUE TITLE
Evaluate Package "peerage"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3231]
Evaluate "peerage" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/peerage

Description: 
Cluster formation library with support for dns-based 
discovery which should work on Kubernetes and Weave.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by rauluranga** [comment]
+1

**Comment by ramonsnir** [comment]
+1
