### ISSUE TITLE
Evaluate Package "social_parse"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3259]
Evaluate "social_parse" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/social_parse

Description: 
A small library for parsing out common social elements such as hashtags, mentions and urls.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by swelham** [comment]
Hi, I have just seen this and of course I would say its awesome! :smile: 

However the link in the issue is missing an "r" at the end.

Working link: [https://hex.pm/packages/social_parser](https://hex.pm/packages/social_parser)
