### ISSUE TITLE
Evaluate Package "sphinxsearch_giza"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3301]
Evaluate "sphinxsearch_giza" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/sphinxsearch_giza

Description: 
Client for the Sphinx search engine

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by Tyler-pierce** [comment]
can close out. sphinxsearch_giza and giza were early attempts and no longer maintained.  giza_sphinxsearch was just added to hex and that one I will continue with (has docs + elixir wrapper for fulltext search queries)
