### ISSUE TITLE
Evaluate Package "numbus"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3307]
Evaluate "numbus" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/numbus

Description: 
Nimbus provide more helpers for Phoenix framework.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by khusnetdinov** [comment]
This hex should be removed from hex.pm. I wrote it to support. Problem that I did mistake then I first time publish this library. Just check my profile and you will see Nimbus hex that in [WIP] https://github.com/khusnetdinov/nimbus

**Comment by h4cc** [comment]
Thanks for that hint. hex.pm says 404.
