### ISSUE TITLE
Add Package "http_router"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#332]
Add the Package "http_router" from hex.pm

Link: https://hex.pm/packages/http_router

**Comment by slogsdon** [comment]
@h4cc I can tackle this

**Comment by slogsdon** [comment]
I just noticed there are more of my libraries in your list of open issues (#325, #318). Would you like one PR for all of them?

**Comment by h4cc** [comment]
Yeah, do as much as you like :)
