### ISSUE TITLE
Evaluate Package "conduit"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3348]
Evaluate "conduit" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/conduit

Description: 
Message queue framework, with support for middleware and multiple adapters.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by blatyo** [comment]
Hi, I'm the author of this library and I obviously thinks it's pretty awesome. What help can I provide?
