### ISSUE TITLE
Evaluate Package "bunq"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3409]
Evaluate "bunq" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/bunq

Description: 
Placeholder package

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by BeginRescue** [comment]
It's a placeholder package created by a user with an email address from bunq.com. Possibly an internal developer. This issue can be closed for now.
