### ISSUE TITLE
Evaluate Package "logi_stdlib_ex"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3427]
Evaluate "logi_stdlib_ex" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/logi_stdlib_ex

Description: 
The standard library for logi_ex

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by acconrad** [comment]
Eh, not so sure here - it's a wrapper of an Erlang library, which I guess is fine, except for the fact that Elixir has Erlang interop built in...so there's really no need for a Erlang wrapper when you can call it directly?
