### ISSUE TITLE
Evaluate Package "conduit_rabbit_common"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3475]
Evaluate "conduit_rabbit_common" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/conduit_rabbit_common

Description: 
RabbitMQ Common Libraries

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by blatyo** [comment]
I pushed this and it's not awesome, it's a temporary stopgap until the rabbitmq guys start pushing the official one.

**Comment by h4cc** [comment]
Thanks for that info :)
