### ISSUE TITLE
Evaluate Package "conduit_amqp_client"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3476]
Evaluate "conduit_amqp_client" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/conduit_amqp_client

Description: 
RabbitMQ AMQP Client

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by blatyo** [comment]
I pushed this and it's not awesome, it's a temporary stopgap until the rabbitmq guys start pushing the official one.

**Comment by h4cc** [comment]
Thanks for that info :)
