### ISSUE TITLE
Evaluate Package "ueberauth_discord"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3482]
Evaluate "ueberauth_discord" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/ueberauth_discord

Description: 
An Uberauth strategy for Discord authentication.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by g33kidd** [comment]
Is it awesome?

**Comment by g33kidd** [comment]
Can confirm, it is awesome.
