### ISSUE TITLE
Evaluate Package "crawlie"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3487]
Evaluate "crawlie" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/crawlie

Description: 
A simple but competent Elixir web crawler library (to be) powered by GenStage.

Don't use the package quite yet please, it's very much a work in progress.
`0.2.0` should be the first relatively useful release.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by nietaki** [comment]
By now (0.4.0) it should be relatively useable and it solves a different problem than [scrape](https://github.com/Anonyfox/elixir-scrape), so I don't think it would be duplicating anything else on the list.

It's got docs, a separate project with examples and is well tested. I'm also back to developing it actively, so having more community exposure/feedback would be a good thing right now.
