### ISSUE TITLE
Evaluate Package "mix_docker"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3496]
Evaluate "mix_docker" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/mix_docker

Description: 
Put your Elixir app production release inside minimal docker image

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by teamon** [comment]
It is!

DISCLAIMER: I might not be objective here for obvious reasons, but I'd love to hear some feedback.

**Comment by teamon** [comment]
FYI mix_docker has been abandoned and deprecated for 4 years now - I don't think it qualifies as "awesome" anymore.
