### ISSUE TITLE
Evaluate Package "crontab"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3539]
Evaluate "crontab" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/crontab

Description: 
Parse Cron Format Strings, Write Cron Format Strings and Caluclate Execution Dates.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by maennchen** [comment]
I'd be very happy to see my package in this list. This is my very first elixir project I'm working on. I'd also be very happy for any feedback that would prevent the package from being listed.

**Comment by h4cc** [comment]
Just make a PR then. Looks great!

Have a look at: https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md
