### ISSUE TITLE
Evaluate Package "workflow"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3620]
Evaluate "workflow" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/workflow

Description: 
Building Blocks to write CQRS Event Sourcing apps in Elixir

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by seanwash** [comment]
Readme mentions some outstanding items that need to be implemented but the repo doesn't seem to have any activity since 2017.
