### ISSUE TITLE
Evaluate Package "slogger"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3633]
Evaluate "slogger" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/slogger

Description: 
Slogger is a simple logger that allows flexible, and easily customizable, module-level control of logging.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by elbow-jason** [comment]
Been pretty awesome so far :)
