### ISSUE TITLE
Evaluate Package "ueberauth_foursquare"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3679]
Evaluate "ueberauth_foursquare" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/ueberauth_foursquare

Description: 
An Ueberauth strategy for using Foursquare to authenticate users.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by acconrad** [comment]
this should be closed, https://github.com/borodiychuk/ueberauth_foursquare is already linked on the awesome-elixir page
