### ISSUE TITLE
Evaluate Package "artifactory"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3697]
Evaluate "artifactory" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/artifactory

Description: 
A Elixir client for Artifactory's REST API

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by djgoku** [comment]
Looks like the code has been removed. The repo is still present though. https://github.com/amorphid/artifactory-elixir
