### ISSUE TITLE
Evaluate Package "enhanced_defstruct"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3705]
Evaluate "enhanced_defstruct" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/enhanced_defstruct

Description: 
EnhancedDefstruct is package that helps to create structs without invoking defmodule macro.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by seanwash** [comment]
Repository has been archived.
