### ISSUE TITLE
Evaluate Package "blogit"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3768]
Evaluate "blogit" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/blogit

Description: 
Blogit is an OTP application for generating blog posts from a git
  repository containing markdown files.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by meddle0x53** [comment]
Blogit can be used as blog engine backend and now it documented: https://hexdocs.pm/blogit/1.0.1/ .
The blog https://blog.elixir-lang.bg is powered by Blogit. It is the blog of the Sofia University Elixir course and is in Bulgarian.
Soon Blogit will support multiple language posts and the blog will have English streams. But yeah, that's Blogit's idea.
