### ISSUE TITLE
Evaluate Package "fun_with_flags"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3780]
Evaluate "fun_with_flags" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/fun_with_flags

Description: 
FunWithFlags, the Elixir feature flag library.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by tompave** [comment]
👍 

But I'm biased as I'm the package author :-)
