### ISSUE TITLE
Evaluate Package "ace_http"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3789]
Evaluate "ace_http" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/ace_http

Description: 
HTTP Server built on top of Ace TCP connection manager

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by CrowdHailer** [comment]
This should be closed. package is deprecated in favour of Ace
