### ISSUE TITLE
Evaluate Package "toolbox"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3876]
Evaluate "toolbox" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/toolbox

Description: 
A library for some common and less common Elixir routines not found in the standard library.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by samvv** [comment]
You should not need to evaluate this package. It has been renamed to `toolbelt`.
