### ISSUE TITLE
Evaluate Package "ex_stub"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#3948]
Evaluate "ex_stub" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/ex_stub

Description: 
ExStub provides an easy way to stub a module to facilitate writing clean, isolated unit tests.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by acconrad** [comment]
Seems like a tiny lib that was made for fun, but not sure if this adds anything that `ex_machina` doesn't already have (technically it's stubs and not factories, but would you want to use this if not factories?)
