### ISSUE TITLE
Evaluate Package "versionary"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#4071]
Evaluate "versionary" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/versionary

Description: 
Elixir plug for handling API versioning

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by anthonator** [comment]
What can I do to get versionary included?

**Comment by fladson** [comment]
@anthonator please see our contributing guide https://github.com/h4cc/awesome-elixir/blob/master/.github/CONTRIBUTING.md
