### ISSUE TITLE
Evaluate Package "expline"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#4145]
Evaluate "expline" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/expline

Description: 
A cubic spline interpolation library for Elixir.

Includes a GenServer. All required Linear Algebra modules are built for the
library, but may be extracted individually.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by isaacsanders** [comment]
Package creator here, to answer questions or help, if needed.
