### ISSUE TITLE
Evaluate Package "emojiclock"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#4192]
Evaluate "emojiclock" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/emojiclock

Description: 
An Elixir module for giving you an emoji clock for a specific hour.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by dunyakirkali** [comment]
Tested with Elixir 1.10.3
