### ISSUE TITLE
Evaluate Package "sippet"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#4206]
Evaluate "sippet" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/sippet

Description: 
An Elixir library designed to be used as SIP protocol middleware.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by balena** [comment]
:+1:

I suggest the section "Protocols" for it.

## Protocols
[sippet](https://github.com/balena/elixir-sippet) - An Elixir library designed to be used as SIP protocol middleware.

**Comment by balena** [comment]
This is the [pull request](https://github.com/h4cc/awesome-elixir/pull/4244).

**Comment by dunyakirkali** [comment]
This issue can be closed right?

**Comment by balena** [comment]
Yes, it can be closed.
