### ISSUE TITLE
Evaluate Package "mockingbird"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#4232]
Evaluate "mockingbird" to see if it's awesome, and possibly include in the list.

Link: https://hex.pm/packages/mockingbird

Description: 
Mockingbird helps you create API consumers that are easy to test.

This is a autogenerated issue, because the packages was added on hex.pm.

**Comment by danbadge** [comment]
Hi, is this something I can help with I helped create Mockingbird?

**Comment by h4cc** [comment]
Just add it to the list in the matching category :D
