### ISSUE TITLE
Add LICENSE information for each package.

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#430]

**Comment by Kosmas** [comment]
@h4cc where do you think this information should go?
Next to the package description in a bracket?

**Comment by h4cc** [comment]
I am currently thinking/working on a heroku elixir app, that will create Badges for LICENSE and number of downloads. These badges could then be appended after the package name maybe.

**Comment by Kosmas** [comment]
OK. Sounds like a good idea!

**Comment by h4cc** [comment]
`Good news everybody!`

The first badge appeared: https://github.com/h4cc/awesome-elixir/tree/h4cc-badges

**Comment by Kosmas** [comment]
:+1:

**Comment by h4cc** [comment]
I am still unsure about such a feature. A dedicated website like beam toolbox might be more usefull in the long run.
