### ISSUE TITLE
A complete payment library for Elixir and Phoenix Framework

### ISSUE THREAD

**Issue by pkrawat1** [h4cc/awesome-elixir#4377]
Add the Package "Gringotts" from hex.pm

Link: https://hexdocs.pm/gringotts/Gringotts.html
Github: https://github.com/aviabird/gringotts

Description:

Gringotts is a payment gateway integration library supporting many gateway integrations. It is in active development right now, and is trending on github.

**Comment by simonewebdesign** [comment]
Closed in #4374
