### ISSUE TITLE
Add package ModestEx

### ISSUE THREAD

**Issue by f34nk** [h4cc/awesome-elixir#4415]
## Title

Add Package "modest_ex"

## Description

**Link:** https://github.com/f34nk/modest_ex

**Description:**

A library to do pipeable transformations on html strings with CSS selectors, e.g. find(), prepend(), append(), replace() etc.

**Comment by f34nk** [comment]
Announcement on the elixirforum: 
https://elixirforum.com/t/modestex-library-to-do-pipeable-transformations-on-html-strings-with-css-selectors/12793

**Comment by simonewebdesign** [comment]
Feel free to make a pull request for it :)
