### ISSUE TITLE
Add section 'HTML' explicitly for html tools

### ISSUE THREAD

**Issue by f34nk** [h4cc/awesome-elixir#4419]
## Title

Add Section "HTML"

## Description

Please add a section "HTML" explicitly for html tools and libraries.
See discussion on the forum: 
https://elixirforum.com/t/overview-of-available-html-tools-in-elixir/12905/3

HTML and XML are completely different languages and should not be represented under the same section. Right now all xml and html related packages are subsumed under the section 'XML'. I think this is misleading.

**Comment by simonewebdesign** [comment]
Closed in #4418

**Comment by simonewebdesign** [comment]
Actually not solved, @f34nk feel free to tackle this one too if you want, so modest_ex can be moved in the new section.
