### ISSUE TITLE
Add package "pow"

### ISSUE THREAD

**Issue by jeroenhouben** [h4cc/awesome-elixir#4606]
## Pow

Add Package "pow"

## Robust, modular, and extendable user authentication system

Add the Package "pow" from hex.pm

**Link:** https://hex.pm/packages/pow

**Description:**

Pow is a robust, modular, and extendable authentication and user management solution for Phoenix and Plug-based apps.

**Comment by iagomoreira** [comment]
I would like to take that one if it's up for grabs.

**Comment by simonewebdesign** [comment]
Please do @iagomoreira :)
