### ISSUE TITLE
Add editor plugin "Nova Elixir"

### ISSUE THREAD

**Issue by alakra** [h4cc/awesome-elixir#4721]
## Title

Add editor plugin "Nova Elixir"

## Description

Add the Package "elixir.novaextension" from github

**Link:** https://github.com/stollcri/elixir.novaextension

**Description:**

Syntax highlighting and code completion for Elixir files (.ex, .exs, .eex) in Nova.

**Comment by simonewebdesign** [comment]
Could you open a PR for this please?

**Comment by alakra** [comment]
Yes! 👍
