### ISSUE TITLE
Add "exor_filter"

### ISSUE THREAD

**Issue by mpope9** [h4cc/awesome-elixir#4728]
## Title

Add Package "exor_filter"

## Description

Add the Package "exor_filter" from GitHub

**Link:** https://github.com/mpope9/exor_bechmark

**Description:**  A nif wrapper around xor_filter.  They're a bloom filter replacement.  Smaller, faster, and less false positives than bloom filters.  Has an API that is compatible with Elixir.

Erlang nif for xor_filter. 'Faster and Smaller Than Bloom and Cuckoo Filters'.

**Comment by simonewebdesign** [comment]
Please open a PR 👍🏼

**Comment by mpope9** [comment]
Can do!
