### ISSUE TITLE
Add pack mongodb_driver

### ISSUE THREAD

**Issue by andreaswillems** [h4cc/awesome-elixir#4731]
## Title

Add Package "mongodb_driver"

## Description

Add the Package "mongodb_driver" from hex.pm (_or another source_)

**Link:** https://hex.pm/packages/mongodb_driver

**Description:**

An alternative MongoDB driver for Elixir.

Support for recent versions of MongoDB (4.4) and seems to have the most comprehensive feature set of all available mongodb drivers for Elixir.

**Comment by simonewebdesign** [comment]
@andreaswillems could you open a PR for this?

**Comment by andreaswillems** [comment]
Sure, thank you for asking.

**Comment by andreaswillems** [comment]
Done.
