### ISSUE TITLE
Add Package "mechanize"

### ISSUE THREAD

**Issue by gushonorato** [h4cc/awesome-elixir#4733]
## Title

Add Package "mechanize"

## Description

Add the Package "mechanize" from Github or hex.pm.

**Link from Github:** https://github.com/gushonorato/mechanize
**Link from Hex:** https://hex.pm/packages/mechanize

**Description:**

Build web scrapers and automate interaction with websites in Elixir with ease!

**Comment by gushonorato** [comment]
Have you added?

**Comment by simonewebdesign** [comment]
No, but feel free to open a PR and I'll merge it

**Comment by gushonorato** [comment]
Done #4810
