### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [h4cc/awesome-elixir#480]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by h4cc** [comment]
Could you please illustrate why and how such a consolidation will be useful?
Who will be associated with "We"?

**Comment by jeffreyjackson** [comment]
you and every other awesome owner out there is considered part of the "we".  I'm just trying to facilitate the following ideas:

1. you'll get more visibility on your repo because all of the awesome repos will be in 1 spot.  When another trends, you'll be more likely to trend as well.
2. with an organization we can have more people focused on making awesome more awesome.  our team can collectively manage PRs together etc.
3.  you wont lose anything, it's still your baby, you'll be an admin in the organization.
4.  it also ensures the continuity of the repos in the case one of the owners stop supporting the repo.  Which is the case we have now with some of the more awesome repos out there.
