### ISSUE TITLE
Add book "Phoenix LiveView Cookbook"

### ISSUE THREAD

**Issue by chrisgreg** [h4cc/awesome-elixir#4866]
## Title

Add book "LiveView Cookbook"

## Description

Add link to the e-book "LiveView Cookbook"

**Link:** https://www.liveviewcookbook.com/

**Description:**

A Phoenix LiveView e-book containing tried and tested recipes for solving common problems

**Comment by simonewebdesign** [comment]
If you send a PR I'll merge it :)
