### ISSUE TITLE
Add Package "benchfella"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#491]
Add the Package "benchfella" from hex.pm

Link: https://hex.pm/packages/benchfella

**Comment by Kosmas** [comment]
@h4cc just noticed that you have a lot issues with 'help wanted' tag. 
is there anything I can help you with?

**Comment by h4cc** [comment]
@Kosmas These tags are added automatically, even this issues are created with every new entry in the hex.pm RSS Feed of new packages.

If you have some spare time and want to help, add as much as you like :D

**Comment by Kosmas** [comment]
@h4cc OK. Is it just a case of adding them to categories as and when they come in?
Anything else that I would need to know before doing a PR?

Any specific way you want me to add them, or should I try a couple and you let me know?

**Comment by h4cc** [comment]
If its a valueable package, simply adding a line to a category. If there is no category creating new categories would be an option too.

Everything else should be in CONTRIBUTING.md.

In the end there is a travis-ci script that will check alphabetic ordering.

**Comment by Kosmas** [comment]
OK. That makes sense.
Any definition of what makes a package valuable?
A certain number of downloads for example?

For this particular new one that we are discussing is just new so you wouldn't add it?

**Comment by h4cc** [comment]
Till now i only rejected a very few packages, because there was no working code in there at all.
Elixir is a quite new language and ecosystem, so every working package is valuable in my eyes.

It also helps to avoid duplicate libraries, if somebody started a lib because he could not find the already existing one.
