### ISSUE TITLE
Add more information to the issue creation.

### ISSUE THREAD

**Issue by Kosmas** [h4cc/awesome-elixir#528]
@h4cc would it be possible to add some more information in the issues from hex?

I'm thinking about package description and maybe total downloads?
Now for every issue we need to go to hex and check.

**Comment by h4cc** [comment]
I tried adding "Description" from RSS feed.
Showing "total download" might not work for a RSS Feed of showing new packages, it should always be < 10 at the time the issue is created ...

**Comment by Kosmas** [comment]
OK. That would be better.
Was not sure where you get them, but now that you mentioned the RSS feed, there is a description there.

As for the downloads I was thinking about all the version downloads.
I think a new version of an existing package is considered 'new' for the RSS feed, so it could have a few more downloads?
For example this one appears on the RSS feed quite recently and it has a few downloads: https://hex.pm/packages/google_sheets

**Comment by h4cc** [comment]
By the way, this awesome list will some day most likely be abonded, because it will be too static with manual editing.

A more flexible and promising project is this one: http://beam-toolbox.com/projects

**Comment by Kosmas** [comment]
Yes, you are probably right.
Until then we have something to do though ;-)

And yes, thanks for the link.
I was thinking that it would be good to have something similar to ruby-toolbox, but it seems Josh has already done that :-)

**Comment by h4cc** [comment]
I have been talking to @knewter, we are planning to work on the beam toolbox :+1:
