### ISSUE TITLE
Add Package "level"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#578]
Add the Package "level" from hex.pm

Link: https://hex.pm/packages/level

Description: Level implements various helper functions and data types for working with Googles Level data store.

Contributors:Martin Gausby

Licenses: MIT

**Comment by h4cc** [comment]
@gausby I am lost - do you know which category this would fit to?

**Comment by gausby** [comment]
It is a wrapper for LevelDB that is a bit more opinionated than Exleveldb. I guess it would go in the same category as Exleveldb.
