### ISSUE TITLE
Add Package "wifi"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#596]
Add the Package "wifi" from hex.pm

Link: https://hex.pm/packages/wifi

Description: Various utility functions for working with the local Wifi network in Elixir.

These functions are mostly useful in scripts that could benefit from knowing

the current location of the computer or the Wifi surroundings.

Contributors:Martin Gausby

Licenses: MIT

**Comment by gausby** [comment]
What kinda help is wanted? ^_^

The module could need some help from Linux- and Windows users. As of yet it only works on Mac OS X machines.

**Comment by h4cc** [comment]
Its just adding the package to the list under the correct category, thats all :D

**Comment by gausby** [comment]
hmm, utilities for working with local wifi ;)

or "Networking", I guess.
