### ISSUE TITLE
Add plataformatec newsletter websites.

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#613]

**Comment by doomspork** [comment]
Would this go under "Reading" or into a new section?

**Comment by h4cc** [comment]
Would go there, but i see now paltaformatec stopped serving these contents: http://pages.plataformatec.com.br/latest-elixir-news-on-the-radar-issue-1

Asked over twitter where these contents went: https://twitter.com/h4cc/status/604928867967610880

**Comment by fladson** [comment]
Still outdated, I'll ask again...
