### ISSUE TITLE
Add Package "redo"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#627]
Add the Package "redo" from hex.pm

Link: https://hex.pm/api/packages/redo

Description: 
Pipelined Redis Erlang Driver

**Comment by doomspork** [comment]
Hey @h4cc, `redo` is already part of awesome-elixir (under ORM and Datamapping).  Did you want to move it?

**Comment by h4cc** [comment]
This issue was generated automatically.
I thing redo is in a category, where most other people might expect to find it.
But as long as "redis" is in the description, the job is done anyway :+1:
