### ISSUE TITLE
Add Package "ddb_client"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#764]
Add the Package "ddb_client" from hex.pm

Link: https://hex.pm/packages/ddb_client

Description: 
DalmatinerDB client

**Comment by fladson** [comment]
Done!

**Comment by fladson** [comment]
@h4cc can we close this?

**Comment by Kentoseth** [comment]
I concur, this should be closed, as it exists on the readme.

@h4cc please look at old issues like this and close them
