### ISSUE TITLE
Add package elixir-primes

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#784]
https://github.com/ewildgoose/elixir-primes

**Comment by acconrad** [comment]
This is a package developed over 2 years ago to generate (and validate) prime numbers. Seems like one of those pet projects that you do with Project Euler, but has no real community benefit. Granted, prime number generation is useful in cryptography, but I might argue that this should be a problem already handled by the vast number of Elixir crypto libraries already available, so I'm not sure how this package on it's own could be useful to the greater community at this point and should probably be closed.

**Comment by h4cc** [comment]
Thanks!
