### ISSUE TITLE
Add Package "expand"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#793]
Add the Package "expand" from hex.pm

Link: https://hex.pm/packages/expand

Description: 
A pretty printer

**Comment by dunyakirkali** [comment]
This module does what it says, but I can't really say that it's awesome. Should I still classify it and make a PR @h4cc ?

**Comment by h4cc** [comment]
@dunyakirkali Thanks, i dont think so :)
This was a automated issue by the way.

**Comment by dunyakirkali** [comment]
Should I prioritize non-automated issues over the automated ones?

(I'm basically trying to help u out with the PR's)

**Comment by h4cc** [comment]
Thanks, the issues do not matter.

If you use a library thats really awesome and often use, these should be the ones i think.
