### ISSUE TITLE
Add Package "cloudinary"

### ISSUE THREAD

**Issue by h4cc** [h4cc/awesome-elixir#866]
Add the Package "cloudinary" from hex.pm

Link: https://hex.pm/packages/cloudinary

Description: 
Library to upload to Cloudinary

**Comment by vysakh0** [comment]
@h4cc I was looking for the docs of this package, couldn't find it (couldn't find the github repo). Can you please link to it?

**Comment by Hajto** [comment]
What's with the documentation?

**Comment by h4cc** [comment]
I asked the author about the package source: https://twitter.com/AwesomeElixir/status/698625971591778305

**Comment by Hajto** [comment]
Too bad he didn't replied.

**Comment by h4cc** [comment]
@r-icarus ping here when created the github repo :)

**Comment by katgironpe** [comment]
I find it not cool to add one without a Github repo. 
I am checking out https://github.com/smeevil/cloudex

**Comment by h4cc** [comment]
Added cloudex, skipping this for now. Thanks!
